package Utils

import java.io.{File, PrintWriter}

class Writer {
  /**
   * Mathod to write generated html code into files
   * @param content The content that was generated by Generator.
   * @param nr The next number to name the file.
   */
  def writeFile(content: String, nr: Int): Unit = {
    val file: File = new File("file" + nr + ".html")
    if (!file.createNewFile()) {
      throw new RuntimeException("Creating new file didn't work!")
    }
    val writer = new PrintWriter(file);
    writer.write(content)
    writer.close()
  }

  /**
   * Method to write all parts of html code that couldn't be discovered successfully into file failure.txt.
   * @param content Parts of html code that couldn't be discovered successfully.
   */
  def writeFailure(content: String): Unit = {
    val file: File = new File("failure.txt")
    if (file.exists()) {
      file.delete()
    }
    val writer = new PrintWriter(file);
    writer.write(content)
    writer.close()
  }
}